### ISSUE TITLE
can't set mysqldump path

### ISSUE THREAD

**Issue by ArroWsGM** [snapcreek/duplicator#289]
Duplicator said `Mysqldump was not found at its default location or the location provided.` but I have mysqldump in a standard location
```
$ which mysqldump
/usr/bin/mysqldump
$ mysqldump --version
mysqldump  Ver 10.14 Distrib 5.5.60-MariaDB, for Linux (x86_64)
```
When I trying to save with path, it switches back to PHP

Duplicator version 1.3.14   (2019-05-20_15:40)

**Comment by lifeinthegrid** [comment]
Hey @Hey @

If you want to submit a <a href='https://snapcreek.com/ticket'>support ticket</a> for this issue we can have a closer look at your setup.  Please provide a link to this thread when submitting the ticket.

Thanks~

If you want to submit a <a href='https://snapcreek.com/ticket'>support ticket</a> for this issue we can have a closer look at your setup.  Please provide a link to this thread when submitting the ticket.

Thanks~

**Comment by ArroWsGM** [comment]
@lifeinthegrid 
I fixed this, the issue is related to open_basedir, and I think, you may provide a little bit more feedback to users in a warning message about mysqldump, or do some changes in the `getMySqlDumpPath` method here:
```
//Try to find a path that works.  With open_basedir enabled, the file_exists may not work on some systems
//So we fallback and try to use exec as a last resort
$exec_available = function_exists('exec');
foreach ($paths as $path) {
//	if (@file_exists($path)) {
		if (DUP_Util::isExecutable($path)) {
			return $path;
		}
//	}
	elseif ($exec_available) {
		$out = array();
		$rc	 = -1;
		$cmd = $path.' --help';
		@exec($cmd, $out, $rc);
		if ($rc === 0) {
			return $path;
		}
	}
}
```
I think `file_exists` dosen't nedded here at all, but I have no time to figured it out now.

**Comment by jkahrs** [comment]
This should have been fixed at https://github.com/snapcreek/duplicator/pull/26/files#diff-4349e69c881ec4857c035b194cb6c9f6
However current master seems to not contain the fix

**Comment by andreamk** [comment]
Hi @ArroWsGM and @jkahrs 

I have review and simplified the getMySqlDumpPath function which should now be fine.
https://github.com/snapcreek/duplicator/compare/20200206_LT_improve_mysqldump_check?expand=1

**Comment by ArroWsGM** [comment]
Thanks @andreamk, but this is not working for me, now just showing a different error message:

> This server does not support the PHP shell_exec function which is required for mysqldump to run.
> Please contact the host or server administrator to enable this feature.
> Please visit our recommended host list for reliable access to mysqldump

instead of

> Mysqldump was not found at its default location or the location provided. Please enter a custom
> path to a valid location where mysqldump can run. If the problem persist contact your host or
> server administrator. See the host list for reliable access to mysqldump.

**Comment by lifeinthegrid** [comment]
Adding correlated threads for reference purposes:
https://wordpress.org/support/topic/mysqldump-detection-wrong/
https://github.com/snapcreek/duplicator/issues/24

**Comment by andreamk** [comment]
@ArroWsGM I added a check on the exec function that if mysqldump is not enabled it can't work. Your problem was probably this.

**Comment by lifeinthegrid** [comment]
@ArroWsGM we have applied additional messages to help alert on that issue it should now be checked into master.    

If any other users on this thread could run a quick check on their environments we can get this patch out soon.    https://github.com/snapcreek/duplicator/archive/master.zip

**Comment by ArroWsGM** [comment]
> @ArroWsGM I added a check on the exec function that if mysqldump is not enabled it can't work. Your problem was probably this.

@andreamk 
Yep, you right, but I have shell_exec enabled, and it works perfectly with my workaround

**Comment by lifeinthegrid** [comment]
After seeing no more requests to the thread we are closing.
