### ISSUE TITLE
Misconfiguration?

### ISSUE THREAD

**Issue by viantirreau** [snapcreek/duplicator#375]
Hey, I noticed in my server logs that some user was able to check a file by using the following url handle

PS: I have the free version of Duplicator

**Comment by bobriley** [comment]
Hi, this does look like an issue. I have changed your question a bit for obvious reasons.  We are looking into this - thank you for contact us - if you have additional questions or want to reach out to us directly please contact admin@snapcreek.com.  Thanks again.

**Comment by lifeinthegrid** [comment]
Hi @viantirreau,

This issue should now be resolved with 1.3.28.   Please let us know if you still see any issues and thanks for reaching out to let us know.

Thanks~

**Comment by viantirreau** [comment]
Hi @lifeinthegrid, 

It is definitely resolved, thanks for the fast response and the awesome plugin!
