### ISSUE TITLE
duplicator_download allow attackers to get wp-config file

### ISSUE THREAD

**Issue by ArroWsGM** [snapcreek/duplicator#384]
Recently we've been attacked  and attackers were able to get our wp-config with this request
```
/?action=duplicator_download&file=../wp-config.php
```
Version 1.3.24 has this security issue, the latest version (1.3.28) is ok.

**Comment by lifeinthegrid** [comment]
Thanks, @ArroWsGM.   This issue has been fixed in 1.3.28 and has been noted in the [changelog](https://snapcreek.com/duplicator/docs/changelog/?lite=1).

**Comment by annettePixie** [comment]
I had the same issue and updated to 1.3.36. It happened again about an hour later.

**Comment by lifeinthegrid** [comment]
Hi annettePixie,

We have not been able to reproduce any of these issues in 1.3.36 based on all of our tests.   Can you please contact us via our help ticket and we can work with you to validate where the issue resides.  Here is the link to connect with us  https://snapcreek.com/ticket.   Please provide a link to this forum so we will know the contact of the ticket.   

Thxs
