### ISSUE TITLE
UI improvement: Use localhost as default on Step 2

### ISSUE THREAD

**Issue by grassfedfarmboi** [snapcreek/duplicator#402]
In Step 2: Install Database, there is a placeholder value of "localhost" for the Host. This was the value I wanted to use, so I filled in the other values and hit "Next." Unfortunately the UI did not accept the placeholder value as a default submitted value as I expected, and I was perturbed to have to go back and type "localhost" over the placeholder by hand before continuing.

Super minor thing that I might even find time to fix myself at some point, but just a heads up!

**Comment by lifeinthegrid** [comment]
Thanks for the feedback!  We have put this in the backlog to look at.

Cheers~

**Comment by lifeinthegrid** [comment]
This should be solved.  Please re-open an issue if any issues persist.
