### ISSUE TITLE
Too few arguments to function DUP_Log::Error()

### ISSUE THREAD

**Issue by ArroWsGM** [snapcreek/duplicator#407]
We have an error in the logger with PHP 7.4
> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function DUP_Log::Error(), 1 passed

I think the best way to resolve the issue is to provide a default for the second param in line 253 of the `./classes/class.logging.php` file:
```
public static function Error($msg, $detail = '', $behavior = Dup_ErrorBehavior::Quit)
```

PS: errors caused by calling `DUP_Log::Error($log_message);` in lines 405 and 416

**Comment by lifeinthegrid** [comment]
Thanks @ArroWsGM!

We will get someone to look at this soon.

**Comment by meistertigran** [comment]
Hi @ArroWsGM 

Here's a patch with the bug fixed - [duplicator-patch.zip](https://github.com/snapcreek/duplicator/files/6177493/duplicator-patch.zip).

Could you please test it out and let me know if it fixed the issue for you?
Thanks,
Tigran.

**Comment by ArroWsGM** [comment]
@meistertigran 
Can't reproduce it anymore, thanks

Actually, I ran into this when trying to investigate dramatically slow MYSQLDUMP (much slower when PHP mode) on windows 10,
but maybe it's my local problem, anyway, if you heard something about it, please let me know

**Comment by lifeinthegrid** [comment]
@ArroWsGM Thanks for the update!

The mysqldump can be slow in some environments!   We have plans to add a parameter for global switches so that you can adjust how mysqldump operates in your environment.    It's possible that it may need additional params for it to run faster.

Thanks~

**Comment by ArroWsGM** [comment]
@lifeinthegrid thanks for the hint
Actually, `mysqldump` itself working fine, I'm tested composed `$cmd` in the terminal. Currently, I have 2 suspects: `popen` or replacing strings on the fly down below and writing them in file with `file_put_contents`

**Comment by lifeinthegrid** [comment]
@ArroWsGM sounds good, let us know if you find anything that might be useful.   I wouldn't think the preg_match would be overly slow but have not done any performance benchmarks on very large files.

One of the approaches we considered taking was to use the "--quick" switch to chunk the results to the file vs dumping the full result from memory into the file.  https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_quick which would help out with hosts that have very low PHP memory requirments.

Thanks~

**Comment by lifeinthegrid** [comment]
Patch for original issue applied to 1.4.1
